import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * One manual sidebar for the whole library — shared top-level guides, then a
 * flat list of components (each its own page + its deep guides + generated API).
 * This is the "one library, always-there component list" shape, not three
 * per-component manuals.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'overview',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/installation', 'getting-started/quick-start'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['guides/accessibility', 'guides/styling', 'guides/form-libraries'],
    },
    {
      type: 'category',
      label: 'Migrating',
      items: [
        'migrating/from-input-otp',
        'migrating/from-react-otp-input',
        'migrating/from-react-currency-input-field',
        'migrating/from-radio-buttons',
        'migrating/from-react-rating',
        'migrating/from-react-stars',
      ],
    },
    { type: 'html', value: 'COMPONENTS', className: 'sidebar-section-header' },
    {
      type: 'category',
      label: 'Currency',
      link: { type: 'doc', id: 'components/currency' },
      items: [
        'components/currency/why',
        'components/currency/localization',
        'components/currency/formatting',
        'components/currency/ui-libraries',
        {
          type: 'category',
          label: 'API',
          items: [{ type: 'autogenerated', dirName: 'components/currency/api' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Rating',
      link: { type: 'doc', id: 'components/rating' },
      items: [
        'components/rating/why',
        'components/rating/display',
        'components/rating/interactive',
        'components/rating/forms',
        'components/rating/custom-icons',
        {
          type: 'category',
          label: 'API',
          items: [{ type: 'autogenerated', dirName: 'components/rating/api' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'OTP',
      link: { type: 'doc', id: 'components/otp' },
      items: [
        'components/otp/why',
        'components/otp/spatial-slots',
        'components/otp/codes-and-autofill',
        'components/otp/webotp',
        'components/otp/forms',
        'components/otp/custom-slots',
        {
          type: 'category',
          label: 'API',
          items: [{ type: 'autogenerated', dirName: 'components/otp/api' }],
        },
      ],
    },
  ],
}

export default sidebars
